// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCslYj7zp7IRVsjweu3zI9z5lfzgJVbZ8',
    appId: '1:78265042413:web:8425c4d7e8a0d8b158d3e4',
    messagingSenderId: '78265042413',
    projectId: 'movinity-a25c2',
    authDomain: 'movinity-a25c2.firebaseapp.com',
    storageBucket: 'movinity-a25c2.firebasestorage.app',
    measurementId: 'G-DYLEMTHHVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4L-MIk2rnMoOINxJ1v1ZOZFmTMG9MZjg',
    appId: '1:78265042413:android:51c1a3f256af2b1558d3e4',
    messagingSenderId: '78265042413',
    projectId: 'movinity-a25c2',
    storageBucket: 'movinity-a25c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNmMUiIm5wc4lhMnZix8HH02LAVknENQ8',
    appId: '1:78265042413:ios:3394c46c41bd7fdf58d3e4',
    messagingSenderId: '78265042413',
    projectId: 'movinity-a25c2',
    storageBucket: 'movinity-a25c2.firebasestorage.app',
    iosBundleId: 'com.example.movinity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNmMUiIm5wc4lhMnZix8HH02LAVknENQ8',
    appId: '1:78265042413:ios:3394c46c41bd7fdf58d3e4',
    messagingSenderId: '78265042413',
    projectId: 'movinity-a25c2',
    storageBucket: 'movinity-a25c2.firebasestorage.app',
    iosBundleId: 'com.example.movinity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCslYj7zp7IRVsjweu3zI9z5lfzgJVbZ8',
    appId: '1:78265042413:web:1d11143122dd914b58d3e4',
    messagingSenderId: '78265042413',
    projectId: 'movinity-a25c2',
    authDomain: 'movinity-a25c2.firebaseapp.com',
    storageBucket: 'movinity-a25c2.firebasestorage.app',
    measurementId: 'G-0CME0VGH4Z',
  );
}
